#mkdir find_biggest_3ds

#fslmaths CHR04_PJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR05_SJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR06_JHJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR08_PJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR09_KRB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR10_LJJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR11_KWS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR12_LSH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR13_KBK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR14_KKS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR15_LCH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR16_KHJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR17_KSM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR18_LYM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR19_KDE/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR20_BKM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR21_HET/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR22_PSJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR23_BJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR24_MJW/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR25_KYS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR26_SYK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR27_JTM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR28_KTH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR29_YSH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR30_OSJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR31_SHB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR34_HHJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR35_JSS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR38_KJC/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR39_LKB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR40_LSH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR41_SSA/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR42_YHS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR43_HSW/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR44_SSW/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR45_JYS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR46_SKH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR47_SDI/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR48_KSY/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR49_LHY/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR50_JHI/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz find_biggest_3ds/added_merged_uptoCHR50.nii.gz

#fslmaths find_biggest_3ds/added_merged_uptoCHR50.nii.gz -add CHR52_CYS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR53_PSS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR54_PSC/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR55_KJB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR56_SJU/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR57_YWY/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR58_CSM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR59_KKH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR60_MJY/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR61_AJB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR62_LHS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR63_BJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR65_JJM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR66_JSK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR67_KJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR68_HBN/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR69_SSW/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR70_YHS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR71_KTJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR72_SSH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR73_HKH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR74_KKH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR75_YJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR76_JYB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR77_JSB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR78_YYJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR79_KDK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR80_NHK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR81_KSK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR82_HJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR83_HJS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR84_IDKB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR85_YSB/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR86_LYH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR87_OKY/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR88_LHJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR89_EJH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR90_KDK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR91_BHM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR92_KYM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR93_NYM/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz find_biggest_3ds/added_merged_uptoCHR93.nii.gz

#fslmaths find_biggest_3ds/added_merged_uptoCHR93.nii.gz -add CHR94_KMK/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR95_YSH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR96_BYS/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR97_SDE/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR98_LKH/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz -add CHR99_LSJ/dual_reg_eachIC/merged_temporal_reg_bp_fnirt_10.nii.gz find_biggest_3ds/added_merged_all.nii.gz

#fslmaths find_biggest_3ds/added_merged_all.nii.gz -div 89 find_biggest_3ds/ave_merged.nii.gz

#fslsplit find_biggest_3ds/ave_merged.nii.gz find_biggest_3ds/ave_resplited_IC -t

find_the_biggest ave_resplited_* biggest_found



