bash nuisance.sh CHR04_PJH
bash nuisance.sh CHR05_SJH
bash nuisance.sh CHR06_JHJ
bash nuisance.sh CHR08_PJH
bash nuisance.sh CHR09_KRB
bash nuisance.sh CHR10_LJJ
bash nuisance.sh CHR11_KWS
bash nuisance.sh CHR12_LSH
bash nuisance.sh CHR13_KBK
bash nuisance.sh CHR14_KKS
bash nuisance.sh CHR15_LCH
bash nuisance.sh CHR16_KHJ
bash nuisance.sh CHR17_KSM
bash nuisance.sh CHR18_LYM
bash nuisance.sh CHR19_KDE
bash nuisance.sh CHR20_BKM
bash nuisance.sh CHR21_HET
bash nuisance.sh CHR22_PSJ
bash nuisance.sh CHR23_BJH
bash nuisance.sh CHR24_MJW
bash nuisance.sh CHR25_KYS
bash nuisance.sh CHR26_SYK
bash nuisance.sh CHR27_JTM
bash nuisance.sh CHR28_KTH
bash nuisance.sh CHR29_YSH
bash nuisance.sh CHR30_OSJ
bash nuisance.sh CHR31_SHB
bash nuisance.sh CHR33_KJK
bash nuisance.sh CHR34_HHJ
bash nuisance.sh CHR35_JSS
bash nuisance.sh CHR38_KJC
bash nuisance.sh CHR39_LKB
bash nuisance.sh CHR40_LSH
bash nuisance.sh CHR41_SSA
bash nuisance.sh CHR42_YHS
bash nuisance.sh CHR43_HSW
bash nuisance.sh CHR44_SSW
bash nuisance.sh CHR45_JYS
bash nuisance.sh CHR46_SKH
bash nuisance.sh CHR47_SDI
bash nuisance.sh CHR48_KSY
bash nuisance.sh CHR49_LHY
bash nuisance.sh CHR50_JHI
bash nuisance.sh CHR52_CYS
bash nuisance.sh CHR53_PSS
bash nuisance.sh CHR54_PSC
bash nuisance.sh CHR55_KJB
bash nuisance.sh CHR56_SJU
bash nuisance.sh CHR57_YWY
bash nuisance.sh CHR58_CSM
bash nuisance.sh CHR59_KKH
bash nuisance.sh CHR60_MJY
bash nuisance.sh CHR61_AJB
bash nuisance.sh CHR62_LHS
bash nuisance.sh CHR63_BJH
bash nuisance.sh CHR65_JJM
bash nuisance.sh CHR66_JSK
bash nuisance.sh CHR67_KJH
bash nuisance.sh CHR68_HBN
bash nuisance.sh CHR69_SSW
bash nuisance.sh CHR70_YHS
bash nuisance.sh CHR71_KTJ
bash nuisance.sh CHR72_SSH
bash nuisance.sh CHR73_HKH
bash nuisance.sh CHR74_KKH
bash nuisance.sh CHR75_YJH
bash nuisance.sh CHR76_JYB
bash nuisance.sh CHR77_JSB
bash nuisance.sh CHR78_YYJ
bash nuisance.sh CHR79_KDK
bash nuisance.sh CHR80_NHK
bash nuisance.sh CHR81_KSK
bash nuisance.sh CHR82_HJH
bash nuisance.sh CHR83_HJS
bash nuisance.sh CHR84_IDKB
bash nuisance.sh CHR85_YSB
bash nuisance.sh CHR86_LYH
bash nuisance.sh CHR87_OKY
bash nuisance.sh CHR88_LHJ
bash nuisance.sh CHR89_EJH
bash nuisance.sh CHR90_KDK
bash nuisance.sh CHR91_BHM
bash nuisance.sh CHR92_KYM
bash nuisance.sh CHR93_NYM
bash nuisance.sh CHR94_KMK
bash nuisance.sh CHR95_YSH
bash nuisance.sh CHR96_BYS
bash nuisance.sh CHR97_SDE
bash nuisance.sh CHR98_LKH
bash nuisance.sh CHR99_LSJ
