python corr.py CHR04_PJH
python corr.py CHR05_SJH
python corr.py CHR06_JHJ
python corr.py CHR08_PJH
python corr.py CHR09_KRB
python corr.py CHR10_LJJ
python corr.py CHR11_KWS
python corr.py CHR12_LSH
python corr.py CHR13_KBK
python corr.py CHR14_KKS
python corr.py CHR15_LCH
python corr.py CHR16_KHJ
python corr.py CHR17_KSM
python corr.py CHR18_LYM
python corr.py CHR19_KDE
python corr.py CHR20_BKM
python corr.py CHR21_HET
python corr.py CHR22_PSJ
python corr.py CHR23_BJH
python corr.py CHR24_MJW
python corr.py CHR25_KYS
python corr.py CHR26_SYK
python corr.py CHR27_JTM
python corr.py CHR28_KTH
python corr.py CHR29_YSH
python corr.py CHR30_OSJ
python corr.py CHR31_SHB
python corr.py CHR33_KJK
python corr.py CHR34_HHJ
python corr.py CHR35_JSS
python corr.py CHR38_KJC
python corr.py CHR39_LKB
python corr.py CHR40_LSH
python corr.py CHR41_SSA
python corr.py CHR42_YHS
python corr.py CHR43_HSW
python corr.py CHR44_SSW
python corr.py CHR45_JYS
python corr.py CHR46_SKH
python corr.py CHR47_SDI
python corr.py CHR48_KSY
python corr.py CHR49_LHY
python corr.py CHR50_JHI
python corr.py CHR52_CYS
python corr.py CHR53_PSS
python corr.py CHR54_PSC
python corr.py CHR55_KJB
python corr.py CHR56_SJU
python corr.py CHR57_YWY
python corr.py CHR58_CSM
python corr.py CHR59_KKH
python corr.py CHR60_MJY
python corr.py CHR61_AJB
python corr.py CHR62_LHS
python corr.py CHR63_BJH
python corr.py CHR65_JJM
python corr.py CHR66_JSK
python corr.py CHR67_KJH
python corr.py CHR68_HBN
python corr.py CHR69_SSW
python corr.py CHR70_YHS
python corr.py CHR71_KTJ
python corr.py CHR72_SSH
python corr.py CHR73_HKH
python corr.py CHR74_KKH
python corr.py CHR75_YJH
python corr.py CHR76_JYB
python corr.py CHR77_JSB
python corr.py CHR78_YYJ
python corr.py CHR79_KDK
python corr.py CHR80_NHK
python corr.py CHR81_KSK
python corr.py CHR82_HJH
python corr.py CHR83_HJS
python corr.py CHR84_IDKB
python corr.py CHR85_YSB
python corr.py CHR86_LYH
python corr.py CHR87_OKY
python corr.py CHR88_LHJ
python corr.py CHR89_EJH
python corr.py CHR90_KDK
python corr.py CHR91_BHM
python corr.py CHR92_KYM
python corr.py CHR93_NYM
python corr.py CHR94_KMK
python corr.py CHR95_YSH
python corr.py CHR96_BYS
python corr.py CHR97_SDE
python corr.py CHR98_LKH
python corr.py CHR99_LSJ
