#bash dual_reg.sh CHR04_PJH
#bash dual_reg.sh CHR05_SJH
#bash dual_reg.sh CHR06_JHJ
#bash dual_reg.sh CHR08_PJH
#bash dual_reg.sh CHR09_KRB
#bash dual_reg.sh CHR10_LJJ
#bash dual_reg.sh CHR11_KWS
#bash dual_reg.sh CHR12_LSH
#bash dual_reg.sh CHR13_KBK
#bash dual_reg.sh CHR14_KKS
#bash dual_reg.sh CHR15_LCH
#bash dual_reg.sh CHR16_KHJ
#bash dual_reg.sh CHR17_KSM
#bash dual_reg.sh CHR18_LYM
#bash dual_reg.sh CHR19_KDE
#bash dual_reg.sh CHR20_BKM
#bash dual_reg.sh CHR21_HET
#bash dual_reg.sh CHR22_PSJ
#bash dual_reg.sh CHR23_BJH
#bash dual_reg.sh CHR24_MJW
#bash dual_reg.sh CHR25_KYS
#bash dual_reg.sh CHR26_SYK
#bash dual_reg.sh CHR27_JTM
#bash dual_reg.sh CHR28_KTH
#bash dual_reg.sh CHR29_YSH
#bash dual_reg.sh CHR30_OSJ
#bash dual_reg.sh CHR31_SHB
#bash dual_reg.sh CHR34_HHJ
#bash dual_reg.sh CHR35_JSS
#bash dual_reg.sh CHR38_KJC
#bash dual_reg.sh CHR39_LKB
#bash dual_reg.sh CHR40_LSH
#bash dual_reg.sh CHR41_SSA
#bash dual_reg.sh CHR42_YHS
#bash dual_reg.sh CHR43_HSW
#bash dual_reg.sh CHR44_SSW
#bash dual_reg.sh CHR45_JYS
#bash dual_reg.sh CHR46_SKH
#bash dual_reg.sh CHR47_SDI
#bash dual_reg.sh CHR48_KSY
#bash dual_reg.sh CHR49_LHY
#bash dual_reg.sh CHR50_JHI
#bash dual_reg.sh CHR52_CYS
#bash dual_reg.sh CHR53_PSS
#bash dual_reg.sh CHR54_PSC
#bash dual_reg.sh CHR55_KJB
#bash dual_reg.sh CHR56_SJU
#bash dual_reg.sh CHR57_YWY
#bash dual_reg.sh CHR58_CSM
#bash dual_reg.sh CHR59_KKH
#bash dual_reg.sh CHR60_MJY
#bash dual_reg.sh CHR61_AJB
#bash dual_reg.sh CHR62_LHS
#bash dual_reg.sh CHR63_BJH
#bash dual_reg.sh CHR65_JJM
#bash dual_reg.sh CHR66_JSK
#bash dual_reg.sh CHR67_KJH
#bash dual_reg.sh CHR68_HBN
#bash dual_reg.sh CHR69_SSW
#bash dual_reg.sh CHR70_YHS
#bash dual_reg.sh CHR71_KTJ
#bash dual_reg.sh CHR72_SSH
#bash dual_reg.sh CHR73_HKH
#bash dual_reg.sh CHR74_KKH
#bash dual_reg.sh CHR75_YJH
#bash dual_reg.sh CHR76_JYB
#bash dual_reg.sh CHR77_JSB
#bash dual_reg.sh CHR78_YYJ
#bash dual_reg.sh CHR79_KDK
#bash dual_reg.sh CHR80_NHK
#bash dual_reg.sh CHR81_KSK
#bash dual_reg.sh CHR82_HJH
#bash dual_reg.sh CHR83_HJS
#bash dual_reg.sh CHR84_IDKB
#bash dual_reg.sh CHR85_YSB
#bash dual_reg.sh CHR86_LYH
#bash dual_reg.sh CHR87_OKY
#bash dual_reg.sh CHR88_LHJ
#bash dual_reg.sh CHR89_EJH
#bash dual_reg.sh CHR90_KDK
#bash dual_reg.sh CHR91_BHM
#bash dual_reg.sh CHR92_KYM
#bash dual_reg.sh CHR93_NYM
#bash dual_reg.sh CHR94_KMK
#bash dual_reg.sh CHR95_YSH
#bash dual_reg.sh CHR96_BYS
#bash dual_reg.sh CHR97_SDE
#bash dual_reg.sh CHR98_LKH
#bash dual_reg.sh CHR99_LSJ
bash dual_reg_eachIC.sh CHR04_PJH
bash dual_reg_eachIC.sh CHR05_SJH
bash dual_reg_eachIC.sh CHR06_JHJ
bash dual_reg_eachIC.sh CHR08_PJH
bash dual_reg_eachIC.sh CHR09_KRB
bash dual_reg_eachIC.sh CHR10_LJJ
bash dual_reg_eachIC.sh CHR11_KWS
bash dual_reg_eachIC.sh CHR12_LSH
bash dual_reg_eachIC.sh CHR13_KBK
bash dual_reg_eachIC.sh CHR14_KKS
bash dual_reg_eachIC.sh CHR15_LCH
bash dual_reg_eachIC.sh CHR16_KHJ
bash dual_reg_eachIC.sh CHR17_KSM
bash dual_reg_eachIC.sh CHR18_LYM
bash dual_reg_eachIC.sh CHR19_KDE
bash dual_reg_eachIC.sh CHR20_BKM
bash dual_reg_eachIC.sh CHR21_HET
bash dual_reg_eachIC.sh CHR22_PSJ
bash dual_reg_eachIC.sh CHR23_BJH
bash dual_reg_eachIC.sh CHR24_MJW
bash dual_reg_eachIC.sh CHR25_KYS
bash dual_reg_eachIC.sh CHR26_SYK
bash dual_reg_eachIC.sh CHR27_JTM
bash dual_reg_eachIC.sh CHR28_KTH
bash dual_reg_eachIC.sh CHR29_YSH
bash dual_reg_eachIC.sh CHR30_OSJ
bash dual_reg_eachIC.sh CHR31_SHB
bash dual_reg_eachIC.sh CHR34_HHJ
bash dual_reg_eachIC.sh CHR35_JSS
bash dual_reg_eachIC.sh CHR38_KJC
bash dual_reg_eachIC.sh CHR39_LKB
bash dual_reg_eachIC.sh CHR40_LSH
bash dual_reg_eachIC.sh CHR41_SSA
bash dual_reg_eachIC.sh CHR42_YHS
bash dual_reg_eachIC.sh CHR43_HSW
bash dual_reg_eachIC.sh CHR44_SSW
bash dual_reg_eachIC.sh CHR45_JYS
bash dual_reg_eachIC.sh CHR46_SKH
bash dual_reg_eachIC.sh CHR47_SDI
bash dual_reg_eachIC.sh CHR48_KSY
bash dual_reg_eachIC.sh CHR49_LHY
bash dual_reg_eachIC.sh CHR50_JHI
bash dual_reg_eachIC.sh CHR52_CYS
bash dual_reg_eachIC.sh CHR53_PSS
bash dual_reg_eachIC.sh CHR54_PSC
bash dual_reg_eachIC.sh CHR55_KJB
bash dual_reg_eachIC.sh CHR56_SJU
bash dual_reg_eachIC.sh CHR57_YWY
bash dual_reg_eachIC.sh CHR58_CSM
bash dual_reg_eachIC.sh CHR59_KKH
bash dual_reg_eachIC.sh CHR60_MJY
bash dual_reg_eachIC.sh CHR61_AJB
bash dual_reg_eachIC.sh CHR62_LHS
bash dual_reg_eachIC.sh CHR63_BJH
bash dual_reg_eachIC.sh CHR65_JJM
bash dual_reg_eachIC.sh CHR66_JSK
bash dual_reg_eachIC.sh CHR67_KJH
bash dual_reg_eachIC.sh CHR68_HBN
bash dual_reg_eachIC.sh CHR69_SSW
bash dual_reg_eachIC.sh CHR70_YHS
bash dual_reg_eachIC.sh CHR71_KTJ
bash dual_reg_eachIC.sh CHR72_SSH
bash dual_reg_eachIC.sh CHR73_HKH
bash dual_reg_eachIC.sh CHR74_KKH
bash dual_reg_eachIC.sh CHR75_YJH
bash dual_reg_eachIC.sh CHR76_JYB
bash dual_reg_eachIC.sh CHR77_JSB
bash dual_reg_eachIC.sh CHR78_YYJ
bash dual_reg_eachIC.sh CHR79_KDK
bash dual_reg_eachIC.sh CHR80_NHK
bash dual_reg_eachIC.sh CHR81_KSK
bash dual_reg_eachIC.sh CHR82_HJH
bash dual_reg_eachIC.sh CHR83_HJS
bash dual_reg_eachIC.sh CHR84_IDKB
bash dual_reg_eachIC.sh CHR85_YSB
bash dual_reg_eachIC.sh CHR86_LYH
bash dual_reg_eachIC.sh CHR87_OKY
bash dual_reg_eachIC.sh CHR88_LHJ
bash dual_reg_eachIC.sh CHR89_EJH
bash dual_reg_eachIC.sh CHR90_KDK
bash dual_reg_eachIC.sh CHR91_BHM
bash dual_reg_eachIC.sh CHR92_KYM
bash dual_reg_eachIC.sh CHR93_NYM
bash dual_reg_eachIC.sh CHR94_KMK
bash dual_reg_eachIC.sh CHR95_YSH
bash dual_reg_eachIC.sh CHR96_BYS
bash dual_reg_eachIC.sh CHR97_SDE
bash dual_reg_eachIC.sh CHR98_LKH
bash dual_reg_eachIC.sh CHR99_LSJ
